#!/usr/bin/env python3
"""
Categorize GitHub starred repos and generate archive documents.
Uses a priority-based matching system to avoid over-categorization.
"""

import json
import os
import sys
from datetime import datetime

# Category definitions with priority keywords (high signal) and secondary keywords
CATEGORIES = {
    "ai-ml": {
        "name": "AI/ML",
        "file": "ai-ml.md",
        "priority": 1,
        "keywords": [
            "ai",
            "ml",
            "llm",
            "gpt",
            "machine-learning",
            "deep-learning",
            "neural-network",
            "nlp",
            "computer-vision",
            "transformer",
            "rag",
            "agent",
            "chatbot",
            "langchain",
            "ollama",
            "openai",
            "anthropic",
            "gen-ai",
            "generative-ai",
            "llm-framework",
            "ai-agents",
            "multi-agent",
            "agentic",
            "prompt",
            "tts",
            "speech",
            "ocr",
            "embedding",
            "vector",
            "inference",
            "pytorch",
            "tensorflow",
            "vllm",
            "fine-tuning",
            "lora",
            "reinforcement",
            "ai-scientist",
            "ai-researcher",
            "ai-assistant",
            "ai-native",
            "ai-storage",
            "ai-gateway",
            "ai-chat",
            "ai-engineering",
            "ai4science",
            "vision-language",
            "vlm",
            "multimodal",
            "text-to-speech",
            "voice",
            "audio",
            "image-generation",
            "diffusion",
            "stable-diffusion",
            "large-language-model",
            "llm-agent",
            "llm-eval",
            "llm-evaluation",
            "llmops",
            "prompt-engineering",
            "prompt-testing",
            "red-teaming",
            "llm-ui",
            "genai",
            "artificial-intelligence",
            "fish-speech",
            "tts",
            "valle",
            "vits",
            "vqgan",
            "vqvae",
            "llama",
            "supervision",
            "yolo",
            "object-detection",
            "instance-segmentation",
            "classification",
            "image-processing",
            "video-processing",
            "tracking",
            "coco",
            "pascal-voc",
            "labelimg",
            "annotations",
            "detection",
            "image-classification",
            "imagenet",
            "recognition",
            "deep-learning",
            "computer-vision",
            "tradingagents",
            "agent",
            "finance",
            "llm",
            "multiagent",
            "trading",
            "trading",
            "algorithmic-trading",
            "quantitative-finance",
            "quant",
            "fintech",
            "investment",
            "stock-market",
            "hedge-fund",
            "ai-hedge-fund",
            "dexter",
            "financial-research",
            "autonomous",
            "deep-financial",
            "valuecell",
            "crypto",
            "equity",
            "stock-market",
            "finance",
            "rever",
            "powered-finance",
            "invoice",
            "qlib",
            "quant-dataset",
            "quant-models",
            "auto-quant",
            "stock-data",
            "moonshot",
            "trading-platform",
            "trading-engine",
            "backtester",
            "vectorized",
            "quantrocket",
            "interactive-brokers",
            "pandas",
            "python",
            "quantitative-finance",
            "deepanalyze",
            "ai-scientist",
            "data-analysis",
            "data-science",
            "jupyter",
            "science",
            "database",
            "deep-research",
            "qwen",
            "bettafish",
            "public-opinion-analysis",
            "sentiment-analysis",
            "deep-search",
            "agent-framework",
            "multi-agent-system",
            "nlp",
            "python3",
            "llms",
            "ruvector",
            "gnn",
            "graph-neural-networks",
            "vector",
            "rust",
            "wasm",
            "onnx",
            "neo4j",
            "low-latency",
            "llm-inference",
            "attention-mechanism",
            "gnns",
            "gnn-model",
            "mincut",
            "graph",
            "ai-ocr",
            "ruview",
            "densepose",
            "esp32",
            "firmware",
            "mcu",
            "monitoring",
            "pose-estimation",
            "rf",
            "self",
            "self-learning",
            "wifi",
            "wifi-hacking",
            "wifi-security",
            "dimos",
            "dimensional",
            "agentic",
            "operating-system",
            "physical-space",
            "vibecode",
            "humanoids",
            "quadrupeds",
            "drones",
            "hardware",
            "natural-language",
            "multi-agent-systems",
            "physical-input",
            "cameras",
            "lidar",
            "actuators",
            "memoria",
            "secure-memory",
            "data-integrity",
            "hallucinations",
            "long-term-context",
            "memory",
            "storage",
            "agent",
            "ai",
            "database",
            "llm",
            "openviking",
            "context-database",
            "context-engineering",
            "filesystem",
            "memory",
            "skill",
            "agentic-rag",
            "ai-agents",
            "clawbot",
            "openclaw",
            "opencode",
            "rag",
            "cognee",
            "ai-memory",
            "cognitive-architecture",
            "cognitive-memory",
            "graph-database",
            "graph-rag",
            "graphrag",
            "knowledge",
            "knowledge-graph",
            "vector-database",
            "toon",
            "token-oriented",
            "compact",
            "human-readable",
            "schema-aware",
            "json",
            "llm-prompts",
            "spec",
            "benchmarks",
            "typescript-sdk",
            "data-format",
            "serialization",
            "tokenization",
            "llm",
            "pipcook",
            "machine-learning",
            "pipeline",
            "tensorflow",
            "js",
            "alibaba",
            "pipcook",
            "machine-learning",
            "platform",
            "web-developers",
            "mineru",
            "document-analysis",
            "extract-data",
            "layout-analysis",
            "ocr",
            "parser",
            "pdf",
            "pdf-converter",
            "pdf-extractor-llm",
            "pdf-extractor-pretrain",
            "pdf-extractor-rag",
            "pdf-parser",
            "autoresearch",
            "ai-agents",
            "research",
            "single-gpu",
            "nanochip",
            "training",
            "automatically",
            "claw-ai-lab",
            "dashboard",
            "research-team",
            "hermes-agent",
            "agent",
            "ai-agent",
            "ai-agents",
            "anthropic",
            "chatgpt",
            "claude",
            "claude-code",
            "clawdbot",
            "codex",
            "hermes",
            "hermes-agent",
            "llm",
            "moltbot",
            "nous-research",
            "openai",
            "openclaw",
            "openharness",
            "open-agent-harness",
            "onyx",
            "ai-chat",
            "chatgpt",
            "chatui",
            "enterprise-search",
            "gen-ai",
            "information-retrieval",
            "llm",
            "llm-ui",
            "nextjs",
            "python",
            "rag",
            "self-hosted",
            "vector-search",
            "deer-flow",
            "agent",
            "agentic",
            "agentic-framework",
            "agentic-workflow",
            "ai",
            "ai-agents",
            "deep-research",
            "harness",
            "langchain",
            "langgraph",
            "langmanus",
            "llm",
            "multi-agent",
            "nodejs",
            "podcast",
            "python",
            "superagent",
            "typescript",
            "cli-anything",
            "making-all-software",
            "agent-native",
            "cli-hub",
            "paperclip",
            "open-source",
            "orchestration",
            "zero-human-companies",
            "edict",
            "ai-agents",
            "ai-orchestration",
            "autonomous-agents",
            "claude",
            "dashboard",
            "kanban",
            "llm",
            "multi-agent",
            "openai",
            "openclaw",
            "orchestration",
            "python",
            "workflow-automation",
            "llm-course",
            "course",
            "large-language-models",
            "llm",
            "machine-learning",
            "roadmap",
            "ai-agents-for-beginners",
            "agentic-ai",
            "agentic-framework",
            "agentic-rag",
            "ai-agents",
            "ai-agents-framework",
            "autogen",
            "generative-ai",
            "semantic-kernel",
            "agency-agents",
            "ai-agency",
            "frontend-wizards",
            "reddit-community-ninjas",
            "whimsy-injectors",
            "reality-checkers",
            "specialized-expert",
            "personality",
            "processes",
            "proven-deliverables",
            "langchain",
            "agents",
            "ai",
            "ai-agents",
            "anthropic",
            "chatgpt",
            "deepagents",
            "enterprise",
            "framework",
            "gemini",
            "generative-ai",
            "langchain",
            "langgraph",
            "llm",
            "multiagent",
            "open-source",
            "openai",
            "pydantic",
            "python",
            "rag",
            "zeroclaw",
            "agent",
            "agentic",
            "ai",
            "infra",
            "ml",
            "openclaw",
            "os",
            "nanoclaw",
            "ai-agents",
            "ai-assistant",
            "claude-code",
            "claude-skills",
            "openclaw",
            "nanobot",
            "ultra-lightweight",
            "personal-ai-agent",
            "nano-vllm",
            "deep-learning",
            "inference",
            "llm",
            "nlp",
            "pytorch",
            "transformer",
            "openclaw",
            "ai",
            "assistant",
            "crustacean",
            "molty",
            "openclaw",
            "own-your-data",
            "personal",
            "oh-my-openagent",
            "omo",
            "ai",
            "ai-agents",
            "amp",
            "anthropic",
            "chatgpt",
            "claude",
            "claude-code",
            "claude-skills",
            "cursor",
            "gemini",
            "ide",
            "openai",
            "opencode",
            "orchestration",
            "tui",
            "typescript",
            "deep-tutor",
            "ai-agents",
            "ai-tutor",
            "clawdbot",
            "cli-tool",
            "deepresearch",
            "interactive-learning",
            "large-language-models",
            "multi-agent-systems",
            "rag",
            "how-to-build-a-coding-agent",
            "agent",
            "ai",
            "cursor",
            "tutorial",
            "workshop",
            "self-llm",
            "chatglm",
            "chatglm3",
            "gemma-2b-it",
            "glm-4",
            "internlm2",
            "llama3",
            "lora",
            "minicpm",
            "q-wen",
            "qwen",
            "qwen1-5",
            "qwen2",
            "minimind-v",
            "artificial-intelligence",
            "chatgpt",
            "vision-language-model",
            "minimind",
            "artificial-intelligence",
            "large-language-model",
            "llm-action",
            "llm",
            "llm-inference",
            "llm-serving",
            "llm-training",
            "llmops",
        ],
    },
    "dev-tools": {
        "name": "开发工具",
        "file": "dev-tools.md",
        "priority": 2,
        "keywords": [
            "coding-agent",
            "skills",
            "commands",
            "package-manager",
            "opencode",
            "openclaw",
            "claude-code",
            "codex",
            "cursor",
            "windsurf",
            "mcp",
            "skills-management",
            "agent-skills",
            "claude-skills",
            "codex-skills",
            "openclaw-skills",
            "opkg",
            "openpackage",
            "gstack",
            "spec-kit",
            "openspec",
            "repomix",
            "zx",
            "cc-switch",
            "ai-tools",
            "desktop-app",
            "provider-management",
            "rust",
            "tauri",
            "wsl-support",
            "baoyu-skills",
            "agent-skills",
            "claude-skills",
            "codex-skills",
            "openclaw-skills",
            "promptfoo",
            "ci",
            "ci-cd",
            "cicd",
            "evaluation",
            "evaluation-framework",
            "llm",
            "llm-eval",
            "llm-evaluation",
            "llm-evaluation-framework",
            "llmops",
            "pentesting",
            "prompt-engineering",
            "prompt-testing",
            "prompts",
            "rag",
            "red-teaming",
            "testing",
            "vulnerability-scanners",
            "cmux",
            "ghostty",
            "terminal",
            "tmux",
            "amp",
            "claude-code",
            "codex",
            "gemini",
            "opencode",
            "ghostty-based",
            "macos",
            "vertical-tabs",
            "notifications",
            "ai-coding-agents",
            "gitnexus",
            "code-intelligence",
            "knowledge-graph",
            "graph-rag",
            "client-side",
            "browser",
            "interactive",
            "code-exploration",
            "scrapling",
            "ai-scraping",
            "automation",
            "crawler",
            "crawling",
            "crawling-python",
            "data",
            "data-extraction",
            "mcp",
            "mcp-server",
            "playwright",
            "python",
            "scraping",
            "selectors",
            "stealth",
            "web-scraper",
            "web-scraping",
            "web-scraping-python",
            "webscraping",
            "xpath",
            "lightpanda",
            "headless-browser",
            "ai",
            "automation",
            "browser",
            "browser-automation",
            "cdp",
            "headless",
            "playwright",
            "puppeteer",
            "zig",
            "pretext",
            "text-measurement",
            "layout",
            "fast",
            "accurate",
            "comprehensive",
            "typescript",
            "porffor",
            "ahead-of-time",
            "javascript-compiler",
            "javascript",
            "ink",
            "react",
            "interactive",
            "command-line",
            "cli",
            "flexbox",
            "javascript",
            "boxen",
            "terminal",
            "boxes",
            "create",
            "dep-tree",
            "cli",
            "dependencies",
            "dependency",
            "dependency-graph",
            "golang",
            "graph",
            "linter",
            "terminal",
            "tree",
            "typescript",
            "npkill",
            "cli",
            "command-line",
            "developer-tools",
            "hacktoberfest",
            "javascript",
            "module",
            "node",
            "nodejs",
            "npm",
            "tool",
            "typescript",
            "odiff",
            "image-comparison",
            "diff",
            "pixel-perfect",
            "snapshot",
            "testing-tool",
            "visual",
            "simd",
            "zig",
            "consola",
            "cli",
            "console",
            "fancy",
            "log",
            "node",
            "terminal",
            "typescript",
            "tinykeys",
            "keybindings",
            "keyboard",
            "shortcut",
            "hotkey",
            "tiny",
            "modern",
            "typescript",
            "file-type",
            "buffer",
            "detect",
            "file",
            "magic",
            "magic-numbers",
            "uint8array",
            "nodejs",
            "perfume",
            "web-performance",
            "performance-monitoring",
            "metrics",
            "monitorning",
            "navigation-timing",
            "network-information",
            "cls",
            "fcp",
            "fid",
            "lcp",
            "tbt",
            "ttfb",
            "web-vitals",
            "core-web-vitals",
            "figlet",
            "ascii",
            "art",
            "font",
            "text",
            "figfont",
            "spec",
            "p-retry",
            "retry",
            "promise",
            "async",
            "function",
            "update-notifier",
            "notification",
            "npm-package",
            "node-module",
            "command-line-utility",
            "update-chec",
            "update-notifier",
            "updater",
            "stacktrace-parser",
            "stack",
            "trace",
            "error",
            "parse",
            "hash",
            "format",
            "tsconfig",
            "bases",
            "extend",
            "runtime",
            "environment",
            "typescript",
            "meriyah",
            "ast",
            "ecmascript",
            "estree",
            "jsx",
            "parser",
            "parsing",
            "performance",
            "stability",
            "tc39",
            "acorn",
            "typescript",
            "ajv",
            "json-schema",
            "validator",
            "typescript",
            "bowser",
            "browser-detection",
            "browser-detector",
            "detect-browsers",
            "device-detection",
            "os-detection",
            "user-agent-parser",
            "useragent",
            "useragentparser",
            "javascript",
            "dompurify",
            "xss",
            "cross-site-scripting",
            "sanitizer",
            "security",
            "prevent-xss-attacks",
            "html",
            "mathml",
            "svg",
            "javascript",
            "comlink",
            "webworkers",
            "web-worker",
            "worker",
            "off-main-thread",
            "proxy",
            "rpc",
            "remote-procedure-call",
            "typescript",
            "memlab",
            "memory-leak",
            "heap",
            "snapshot",
            "leak",
            "detector",
            "facebook",
            "hermes",
            "javascript",
            "nodejs",
            "perf-tools",
            "performance",
            "v8",
            "e2e",
            "numbro",
            "formatting",
            "numbers",
            "javascript",
            "hacktoberfest",
            "dinero",
            "money",
            "currency",
            "monetary",
            "amount",
            "immutable",
            "typescript",
            "javascript",
            "web-push",
            "push",
            "notification",
            "node",
            "nodejs",
            "javascript",
            "re2",
            "regex",
            "regular-expression",
            "pcre",
            "perl",
            "safe",
            "fast",
            "thread-friendly",
            "c++",
            "fflate",
            "compression",
            "decompression",
            "zlib",
            "pako",
            "tiny",
            "high-performance",
            "typescript",
            "pinyin",
            "chinese",
            "hanzi",
            "zhongwen",
            "javascript",
            "mammoth",
            "docx",
            "word",
            "html",
            "convert",
            "javascript",
            "file-saver",
            "saveas",
            "filesaver",
            "blob",
            "download",
            "javascript",
            "mime",
            "mime-types",
            "javascript",
            "typescript",
            "8cc",
            "c-compiler",
            "c",
            "small",
            "compiler",
            "exifreader",
            "exif",
            "javascript",
            "image",
            "metadata",
            "exifr",
            "exif",
            "gps",
            "heic",
            "icc",
            "iptc",
            "jfif",
            "jpg",
            "metadata",
            "orientation",
            "parser",
            "photo",
            "png",
            "tiff",
            "xmp",
            "javascript",
            "libimagequant",
            "palette",
            "quantization",
            "pngquant",
            "image-optimization",
            "image-pixels",
            "minification",
            "palette-generation",
            "pixel-array",
            "quality",
            "rgba-pixels",
            "rust",
            "gpu.js",
            "gpu",
            "glsl",
            "gpgpu",
            "math",
            "nodejs",
            "webgl",
            "javascript",
        ],
    },
    "frontend": {
        "name": "前端开发",
        "file": "frontend.md",
        "priority": 3,
        "keywords": [
            "react",
            "vue",
            "angular",
            "svelte",
            "nextjs",
            "nuxt",
            "frontend",
            "ui",
            "component",
            "css",
            "tailwind",
            "webpack",
            "vite",
            "javascript",
            "typescript",
            "html",
            "dom",
            "browser",
            "web",
            "webapp",
            "page-transitions",
            "animation",
            "spa",
            "single-page-application",
            "flexbox",
            "interactive",
            "command-line",
            "reveal",
            "presentation",
            "slides",
            "slideshow",
            "html",
            "javascript",
            "excalidraw",
            "whiteboard",
            "collaboration",
            "diagrams",
            "drawing",
            "hacktoberfest",
            "productivity",
            "canvas",
            "typescript",
            "blocksuite",
            "block-editor",
            "collaboration",
            "components",
            "components-library",
            "crdt",
            "editor",
            "local-first",
            "notion-editor",
            "rich-text-editor",
            "state-management",
            "webcomponents",
            "wysiwyg",
            "wysiwyg-editor",
            "yjs",
            "typescript",
            "yjs",
            "shared-editing",
            "realtime",
            "peer-to-peer",
            "p2p",
            "decentralized",
            "offline-first",
            "collaborative-editing",
            "crdt",
            "javascript",
            "vue-starport",
            "shared-component",
            "routes",
            "animations",
            "typescript",
            "barba",
            "animation",
            "barbajs",
            "css",
            "fluid",
            "library",
            "page",
            "page-transitions",
            "plugin-system",
            "prefetch",
            "router",
            "single-page-application",
            "smooth",
            "spa",
            "transition",
            "typescript",
            "aframe",
            "virtual-reality",
            "vr",
            "ar",
            "augmented-reality",
            "webgl",
            "threejs",
            "metaverse",
            "gamedev",
            "game-engine",
            "3d",
            "html",
            "javascript",
            "shiny",
            "css",
            "devicemotion",
            "javascript",
            "light",
            "mobile",
            "motion",
            "body-scroll-lock",
            "angular",
            "body-scroll",
            "bsl",
            "chrome",
            "freeze",
            "ios",
            "lightbox",
            "lock",
            "mobile",
            "modal",
            "overflow",
            "react",
            "react-scroll-lock",
            "react-scrolllock",
            "safari",
            "scroll-lock",
            "toggle",
            "vanilla-js",
            "vuejs",
            "javascript",
            "pulltorefresh",
            "javascript",
            "js",
            "pulltorefresh",
            "scroll-out",
            "animation",
            "css",
            "css-classes",
            "javascript",
            "scroll-events",
            "scrolling",
            "transition",
            "typescript",
            "viselect",
            "dom-selection",
            "javascript-library",
            "js-library",
            "preact",
            "react",
            "select",
            "selection",
            "selections",
            "ui",
            "ux-design",
            "ux-experience",
            "viselect",
            "vue",
            "typescript",
            "scroll-hint",
            "es6",
            "js",
            "npm",
            "ui",
            "javascript",
            "cleave-zen",
            "credit-card",
            "creditcard",
            "formatting",
            "input",
            "typescript",
            "typed",
            "typing",
            "animation",
            "library",
            "javascript",
            "photoswipe",
            "gallery",
            "image",
            "javascript",
            "lightbox",
            "mobile",
            "desktop",
            "modular",
            "framework-independent",
            "xgplayer",
            "dash",
            "flv",
            "flv-parser",
            "fmp4",
            "hls",
            "hls-player",
            "html5-video",
            "html5-video-player",
            "mp4",
            "mp4box",
            "player",
            "video",
            "video-player",
            "videoplayer",
            "javascript",
            "bytedance",
            "remotion",
            "javascript",
            "react",
            "video",
            "make-videos",
            "programmatically",
            "typescript",
            "faker",
            "browser",
            "data",
            "fake",
            "faker",
            "javascript",
            "nodejs",
            "typescript",
            "fingerprintjs",
            "audio-fingerprinting",
            "browser-fingerprint",
            "browser-fingerprinting",
            "detection",
            "fingerprint",
            "fingerprinting",
            "fraud",
            "fraud-detection",
            "identification",
            "javascript",
            "visitor-identifier",
            "typescript",
            "flexsearch",
            "elasticsearch",
            "full-text-search",
            "fulltext-search",
            "fuzzy",
            "fuzzy-search",
            "javascript",
            "javascript-library",
            "nodejs",
            "open-source",
            "search",
            "search-algorithm",
            "search-engine",
            "search-in-text",
            "searching",
            "searching-algorithms",
            "web",
            "web-worker",
            "fuse",
            "bitap",
            "javascript",
            "lightweight-fuzzy-search",
            "weighted-search",
            "awesome-canvas",
            "2d",
            "3d",
            "awesome",
            "awesome-canvas",
            "awesome-list",
            "canvas",
            "canvas-element",
            "canvas-game",
            "canvas2d",
            "chart",
            "draw",
            "echarts",
            "excel",
            "flowchart",
            "gantt",
            "html2canvas",
        ],
    },
    "backend": {
        "name": "后端开发",
        "file": "backend.md",
        "priority": 4,
        "keywords": [
            "api",
            "server",
            "backend",
            "framework",
            "database",
            "orm",
            "graphql",
            "rest",
            "microservice",
            "go",
            "python",
            "java",
            "rust",
            "node",
            "express",
            "django",
            "fastapi",
            "spring",
            "flask",
            "sqlalchemy",
            "postgres",
            "mysql",
            "mongodb",
            "redis",
            "elasticsearch",
            "kafka",
            "rabbitmq",
            "grpc",
            "protobuf",
            "thrift",
            "avro",
            "message-queue",
            "event-driven",
            "service-mesh",
            "api-gateway",
            "load-balancer",
            "reverse-proxy",
            "nginx",
            "caddy",
            "traefik",
            "haproxy",
            "envoy",
            "istio",
            "linkerd",
            "consul",
            "vault",
            "nomad",
            "packer",
            "terraform",
            "pulumi",
            "cloudformation",
            "serverless",
            "lambda",
            "function",
            "edge",
            "cdn",
            "object-storage",
            "s3",
            "minio",
            "ceph",
            "glusterfs",
            "nfs",
            "cifs",
            "smb",
            "ftp",
            "sftp",
            "scp",
            "rsync",
            "ssh",
            "telnet",
            "http",
            "https",
            "websocket",
            "mqtt",
            "amqp",
            "stomp",
            "xmpp",
            "sip",
            "rtsp",
            "rtmp",
            "hls",
            "dash",
            "webrtc",
            "sctp",
            "quic",
            "http2",
            "http3",
            "tcp",
            "udp",
            "ip",
            "dns",
            "dhcp",
            "ntp",
            "smtp",
            "pop3",
            "imap",
            "ldap",
            "kerberos",
            "oauth",
            "openid",
            "saml",
            "jwt",
            "jwe",
            "jws",
            "jwk",
            "jwks",
            "higress",
            "ai-gateway",
            "ai-native",
            "api-gateway",
            "cloud-native",
            "envoy",
            "go",
            "alibaba",
            "zvec",
            "lightweight",
            "lightning-fast",
            "in-process",
            "vector-database",
            "agent-memory",
            "ann-search",
            "embedded-database",
            "local",
            "nodejs",
            "python",
            "rag",
            "vector-search",
            "vectordb",
            "c++",
            "alibaba",
            "rustfs",
            "s3",
            "object-storage",
            "ai-native",
            "ai-storage",
            "amazon-s3",
            "bigdata",
            "cloud-native",
            "filesystem",
            "minio",
            "multi-cloud",
            "objectstorage",
            "rust",
            "netsonar",
            "network",
            "pings",
            "utilities",
            "c#",
            "tiny8",
            "cpu-simulator",
            "python",
            "8-bit-computer",
            "assembler",
            "visualization",
            "servbay",
            "webdev",
            "web",
            "database",
            "mariadb",
            "memcached",
            "mysql",
            "nginx",
            "nodejs",
            "php",
            "phpmyadmin",
            "postgresql",
            "redis",
            "caddy",
        ],
    },
    "devops": {
        "name": "DevOps",
        "file": "devops.md",
        "priority": 5,
        "keywords": [
            "docker",
            "kubernetes",
            "k8s",
            "container",
            "containerd",
            "podman",
            "lxc",
            "lxd",
            "vm",
            "virtual-machine",
            "hypervisor",
            "qemu",
            "kvm",
            "virtualbox",
            "vmware",
            "hyper-v",
            "xen",
            "proxmox",
            "openstack",
            "cloudstack",
            "cloud",
            "aws",
            "gcp",
            "azure",
            "alicloud",
            "tencent-cloud",
            "huawei-cloud",
            "digitalocean",
            "linode",
            "vultr",
            "hetzner",
            "ovh",
            "scaleway",
            "upcloud",
            "ionos",
            "exoscale",
            "kamatera",
            "hostinger",
            "bluehost",
            "godaddy",
            "namecheap",
            "cloudflare",
            "fastly",
            "akamai",
            "cloudfront",
            "lima",
            "lima-vm",
            "macos",
            "qemu",
            "vm",
            "containerd",
            "go",
            "mkcert",
            "https",
            "tls",
            "certificates",
            "local-development",
            "localhost",
            "root-ca",
            "chrome",
            "firefox",
            "ios",
            "linux",
            "macos",
            "windows",
            "go",
        ],
    },
    "data-science": {
        "name": "数据科学",
        "file": "data-science.md",
        "priority": 6,
        "keywords": [
            "data-science",
            "data-analysis",
            "data-visualization",
            "pandas",
            "numpy",
            "jupyter",
            "etl",
            "data-pipeline",
            "analytics",
            "dashboard",
            "chart",
            "plot",
            "graph",
            "visualization",
            "data-engineering",
            "data-warehouse",
            "data-lake",
            "data-mart",
            "data-mesh",
            "data-fabric",
            "data-catalog",
            "data-governance",
            "data-quality",
            "data-lineage",
        ],
    },
    "security": {
        "name": "安全工具",
        "file": "security.md",
        "priority": 7,
        "keywords": [
            "security",
            "pentest",
            "hacking",
            "encryption",
            "vulnerability",
            "scanner",
            "audit",
            "auth",
            "oauth",
            "jwt",
            "cryptography",
            "cybersecurity",
            "penetration-testing",
            "security-audit",
            "security-automation",
            "security-tools",
            "red-team",
            "blue-team",
            "purple-team",
            "threat-modeling",
            "threat-intelligence",
            "threat-hunting",
            "incident-response",
            "forensics",
            "malware",
            "ransomware",
            "phishing",
            "social-engineering",
            "exploit",
            "zero-day",
            "cve",
            "vulnerability-management",
            "patch-management",
            "configuration-management",
            "compliance",
            "regulation",
            "standard",
            "framework",
            "policy",
            "procedure",
            "guideline",
            "best-practice",
            "checklist",
            "benchmark",
            "baseline",
            "hardening",
            "secure",
            "shannon",
            "ai-pentester",
            "web-applications",
            "apis",
            "source-code",
            "attack-vectors",
            "exploits",
            "vulnerabilities",
            "production",
            "penetration-testing",
            "pentesting",
            "security-audit",
            "security-automation",
            "security-tools",
            "typescript",
            "strix",
            "ai-hackers",
            "vulnerabilities",
            "agents",
            "artificial-intelligence",
            "cybersecurity",
            "generative-ai",
            "llm",
            "python",
            "personal-security-checklist",
            "privacy",
            "protection",
            "censorship",
            "surveillance",
            "defense",
            "hacktoberfest",
            "open-source",
            "security-tools",
            "awesome",
            "awesome-list",
            "checklist",
            "cybersecurity",
            "typescript",
        ],
    },
    "learning": {
        "name": "学习资源",
        "file": "learning.md",
        "priority": 8,
        "keywords": [
            "tutorial",
            "course",
            "book",
            "learn",
            "awesome",
            "guide",
            "roadmap",
            "cheatsheet",
            "educational",
            "科普",
            "workshop",
            "training",
            "study",
            "practice",
            "exercise",
            "example",
            "demo",
            "sample",
            "template",
            "starter",
            "boilerplate",
            "scaffold",
            "kickstart",
            "bootstrap",
            "introduction",
            "beginner",
            "intermediate",
            "advanced",
            "expert",
            "master",
            "professional",
            "certification",
            "degree",
            "diploma",
            "certificate",
            "llm-course",
            "course",
            "large-language-models",
            "llm",
            "machine-learning",
            "roadmap",
            "build-your-own-x",
            "programming",
            "tutorial-code",
            "tutorial-exercises",
            "tutorials",
            "free",
            "awesome-list",
            "professional-programming",
            "computer-science",
            "concepts",
            "documentation",
            "engineer",
            "learning",
            "lessons-learned",
            "programmer",
            "programming-language",
            "read-articles",
            "scalability",
            "software-engineering",
            "architecture",
            "python",
            "comprehensive-rust",
            "android",
            "classroom",
            "course",
            "google",
            "guide",
            "rust",
            "training",
            "training-materials",
            "howto-make-more-money",
            "程序员",
            "零花钱",
            "php",
            "opc-methodology",
            "一人企业",
            "副业",
            "自媒体",
            "电商",
            "数字商品",
            "lean-side-bussiness",
            "精益副业",
            "程序员",
            "优雅地",
            "gold-miner",
            "掘金",
            "翻译",
            "英译中",
            "技术社区",
            "translation",
            "tutorials",
            "ai",
            "android",
            "frontend",
            "ios",
            "javascript",
            "react",
            "swift",
            "tensorflow",
            "one-small-step",
            "技术科普",
            "教程",
            "python",
            "awesome-public-datasets",
            "aaron-swartz",
            "datasets",
            "opendata",
            "awesome-mac",
            "app",
            "apple",
            "application",
            "apps",
            "awesome",
            "awesome-list",
            "awesome-lists",
            "awesome-mac",
            "desktop-app",
            "desktop-application",
            "desktop-apps",
            "list",
            "mac",
            "mac-osx",
            "macos",
            "macos-app",
            "macos-apps",
            "macosx",
            "software",
            "swift",
            "startup-marketing-checklist",
            "automation",
            "marketing",
            "startups",
            "tools",
            "checklist",
            "tactics",
            "500-ai-agents-projects",
            "ai-agents",
            "genai",
            "curated",
            "use-cases",
            "industries",
            "open-source",
            "implementation",
            "healthcare",
            "finance",
            "education",
            "retail",
            "awesome-prompts",
            "awesome",
            "awesome-list",
            "chatgpt",
            "gpt4",
            "gpts",
            "gptstore",
            "papers",
            "prompt",
            "prompt-engineering",
            "how-to-ask-questions",
            "rtfm",
            "stfw",
            "translation",
            "javascript",
            "system-prompts-and-models",
            "ai",
            "bolt",
            "cluely",
            "copilot",
            "cursor",
            "cursorai",
            "devin",
            "github-copilot",
            "lovable",
            "open-source",
            "perplexity",
            "replit",
            "system-prompts",
            "trae",
            "trae-ai",
            "trae-ide",
            "v0",
            "vscode",
            "windsurf",
            "windsurf-ai",
        ],
    },
    "productivity": {
        "name": "效率工具",
        "file": "productivity.md",
        "priority": 9,
        "keywords": [
            "note",
            "task",
            "todo",
            "automation",
            "workflow",
            "productivity",
            "timer",
            "calendar",
            "email",
            "markdown",
            "obsidian",
            "notion",
            "knowledge-base",
            "wiki",
            "documentation",
            "doc",
            "write",
            "editor",
            "text",
            "rich-text",
            "wysiwyg",
            "collaboration",
            "collaborative",
            "team",
            "project-management",
            "kanban",
            "scrum",
            "agile",
            "sprint",
            "backlog",
            "memos",
            "note-taking",
            "memo",
            "microblog",
            "notecard",
            "own-your-data",
            "social-network",
            "sqlite",
            "docker",
            "foss",
            "go",
            "markdown",
            "react",
            "self-hosted",
            "summarize",
            "cli",
            "summarize",
            "typescript",
            "ai",
            "wttr",
            "weather",
            "curl",
            "ascii-art",
            "terminal",
            "weather-api",
            "weather-app",
            "weather-information",
            "python",
            "worldmonitor",
            "dashboard",
            "ai",
            "geopolitics",
            "monitoring",
            "news",
            "opensource",
            "osint",
            "palantir",
            "situation",
            "real-time",
            "global-intelligence",
            "ai-powered",
            "news-aggregation",
            "geopolitical-monitoring",
            "infrastructure-tracking",
            "unified",
            "situational-awareness",
            "interface",
            "typescript",
            "resume-matcher",
            "applicant-tracking-system",
            "ats",
            "hacktoberfest",
            "machine-learning",
            "natural-language-processing",
            "nextjs",
            "python",
            "resume",
            "resume-builder",
            "resume-parser",
            "text-similarity",
            "typescript",
            "vector-search",
            "word-embeddings",
        ],
    },
    "other": {
        "name": "其他",
        "file": "other.md",
        "priority": 10,
        "keywords": [],
    },
}


def categorize_repo(repo):
    """Categorize a single repo using priority-based matching."""
    topics = [t.lower() for t in (repo.get("topics") or [])]
    description = (repo.get("description") or "").lower()
    language = (repo.get("language") or "").lower()
    full_name = (repo.get("full_name") or "").lower()

    text = " ".join(topics + [description] + [language] + [full_name])

    best_category = "other"
    best_score = 0
    best_priority = 999

    for cat_id, cat_info in CATEGORIES.items():
        if cat_id == "other":
            continue
        score = 0
        for keyword in cat_info["keywords"]:
            if keyword.lower() in text:
                score += 1
        # Only update if this category has more matches, or same matches but higher priority
        if score > best_score or (
            score == best_score and score > 0 and cat_info["priority"] < best_priority
        ):
            best_score = score
            best_priority = cat_info["priority"]
            best_category = cat_id

    return best_category


def format_date(date_str):
    """Format ISO date to readable string."""
    if not date_str:
        return "N/A"
    try:
        dt = datetime.fromisoformat(date_str.replace("Z", "+00:00"))
        return dt.strftime("%Y-%m-%d")
    except (ValueError, AttributeError):
        return date_str[:10] if date_str else "N/A"


def format_stars(count):
    """Format star count."""
    if count >= 1000:
        return f"{count / 1000:.1f}k"
    return str(count)


def generate_repo_entry(repo):
    """Generate markdown entry for a single repo."""
    name = repo.get("full_name", "Unknown")
    url = repo.get("html_url", "#")
    desc = repo.get("description") or "暂无描述"
    lang = repo.get("language") or "N/A"
    stars = repo.get("stargazers_count", 0)
    pushed = format_date(repo.get("pushed_at"))
    topics = repo.get("topics") or []

    entry = f"### [{name}]({url})\n\n"
    entry += f"- **描述**: {desc}\n"
    entry += f"- **语言**: {lang}\n"
    entry += f"- **Stars**: ⭐ {format_stars(stars)} ({stars:,})\n"
    entry += f"- **最后更新**: {pushed}\n"
    if topics:
        entry += f"- **标签**: {', '.join(topics[:10])}\n"
    entry += "\n"
    return entry


def generate_category_doc(repos, category_id, category_info):
    """Generate markdown document for a category."""
    title = category_info["name"]
    lines = [f"# {title}\n"]
    lines.append(f"> 共 {len(repos)} 个仓库\n")

    for repo in repos:
        lines.append(generate_repo_entry(repo))

    return "\n".join(lines)


def generate_readme(category_counts, total):
    """Generate README.md with overview."""
    lines = [
        "# GitHub Stars 归档",
        "",
        f"> 自动生成于 {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "## 总览",
        "",
        f"共 **{total}** 个 starred 仓库，分为以下类别：",
        "",
        "| 类别 | 数量 | 占比 |",
        "|------|------|------|",
    ]

    for cat_id, count in sorted(category_counts.items(), key=lambda x: -x[1]):
        cat_info = CATEGORIES.get(cat_id, CATEGORIES["other"])
        pct = f"{count / total * 100:.1f}%" if total > 0 else "0%"
        lines.append(f"| {cat_info['name']} | {count} | {pct} |")

    lines.append("")
    lines.append("## 按日期归档")
    lines.append("")
    lines.append("完整的按日期归档文件见各 `stars-archive-*.md` 文件。")
    lines.append("")
    lines.append("## 按分类查看")
    lines.append("")

    for cat_id, cat_info in CATEGORIES.items():
        if cat_id == "other":
            continue
        if cat_id in category_counts:
            lines.append(f"- [{cat_info['name']}](by-category/{cat_info['file']})")

    if "other" in category_counts:
        lines.append(f"- [其他](by-category/{CATEGORIES['other']['file']})")
    lines.append("")

    return "\n".join(lines)


def main():
    if len(sys.argv) < 2:
        print("Usage: python categorize_stars.py <stars.json> [output_dir]")
        sys.exit(1)

    stars_file = sys.argv[1]
    output_dir = sys.argv[2] if len(sys.argv) > 2 else "docs/github-stars"

    with open(stars_file, "r", encoding="utf-8") as f:
        repos = json.load(f)

    print(f"Loaded {len(repos)} starred repos")

    # Categorize
    categories = {cat_id: [] for cat_id in CATEGORIES}
    for repo in repos:
        cat = categorize_repo(repo)
        categories[cat].append(repo)

    # Print summary
    print("\n分类统计:")
    for cat_id, cat_repos in sorted(categories.items(), key=lambda x: -len(x[1])):
        cat_info = CATEGORIES[cat_id]
        print(f"  {cat_info['name']}: {len(cat_repos)}")

    # Create output directories
    os.makedirs(output_dir, exist_ok=True)
    os.makedirs(os.path.join(output_dir, "by-category"), exist_ok=True)

    # Generate category docs
    for cat_id, cat_repos in categories.items():
        if not cat_repos:
            continue
        cat_info = CATEGORIES[cat_id]
        doc = generate_category_doc(cat_repos, cat_id, cat_info)
        filepath = os.path.join(output_dir, "by-category", cat_info["file"])
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(doc)

    # Generate README
    category_counts = {
        cat_id: len(repos) for cat_id, repos in categories.items() if repos
    }
    readme = generate_readme(category_counts, len(repos))
    with open(os.path.join(output_dir, "README.md"), "w", encoding="utf-8") as f:
        f.write(readme)

    # Generate date-based archive
    today = datetime.now().strftime("%Y-%m-%d")
    archive_lines = [
        f"# Stars 归档 - {today}",
        "",
        f"> 共 {len(repos)} 个仓库，按 star 时间排序",
        "",
    ]
    for repo in repos:
        archive_lines.append(generate_repo_entry(repo))

    archive_file = os.path.join(output_dir, f"stars-archive-{today}.md")
    with open(archive_file, "w", encoding="utf-8") as f:
        f.write("\n".join(archive_lines))

    print(f"\n归档完成！输出目录: {output_dir}")


if __name__ == "__main__":
    main()
